name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wyze/discord-bot:latest
          secrets: |
            "dotenv=DEFINED_API_KEY=${{ secrets.DEFINED_API_KEY }}
            DEFINED_URL=${{ secrets.DEFINED_URL }}
            MARKETPLACE_URL=${{ secrets.MARKETPLACE_URL }}"
